#pragma once
#define DAP_VERSION_CONFIG 164

// define the payload types
#define DAP_PAYLOAD_TYPE_CONFIG 100
#define DAP_PAYLOAD_TYPE_ACTION 110
#define DAP_PAYLOAD_TYPE_STATE_BASIC 120
#define DAP_PAYLOAD_TYPE_STATE_EXTENDED 130
#define DAP_PAYLOAD_TYPE_ESPNOW_PAIRING 140
#define DAP_PAYLOAD_TYPE_ESPNOW_RUDDER 150
#define DAP_PAYLOAD_TYPE_ESPNOW_JOYSTICK 160
#define DAP_PAYLOAD_TYPE_BRIDGE_STATE 210
#define DAP_PAYLOAD_TYPE_ACTION_OTA 220
#define DAP_PAYLOAD_TYPE_ESPNOW_LOG 225
#define DAP_PAYLOAD_TYPE_ASSIGNMENT 230



#define SOF_BYTE_0 0xAA
#define SOF_BYTE_1 0x55
#define EOF_BYTE_0 0xAA
#define EOF_BYTE_1 0x56

#define ASSIGNMENT_EEPROM_OFFSET 9